version: '3.4'

networks:
  dev:
    driver: bridge

services:
  todoapi:
    image: todoapi
    container_name: "todoapi-services"
    ports:
      - "7031:7031"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:7031
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings_DefaultConnection=User ID=postgres;Password=postgres;Server=localhost;Port=5432;Database=SampleDbDriver' IntegratedSecurity=true;Pooling=true
    networks:
      - dev
  
  app_db:
    image: postgres:latest
    user: postgres
    container_name: app_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=SampleDbDriver
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - app_data:/var/lib/postgresql/data
    networks:
      - dev
        
volumes:
  app_data:
        
