version: '3.4'

networks:
  dev:
    driver: bridge

services:
  todoapi:
    image: todoapi
    container_name: "todoapi-services"
    ports:
      - "7031:7031"
      - "5021:5021"
      - "7000:7000"
    command: bash -c "dotnet ef database update --context DataBaseContext && dotnet run --urls=http://0.0.0.0:7000"
    depends_on:
      - app_db
    build:
      context: .
    environment:
      #- ASPNETCORE_URLS=http://+:7031
      - ASPNETCORE_ENVIRONMENT=Development
  
  app_db:
    image: postgres:latest
    user: postgres
    container_name: app_db
    environment:
      - POSTGRES_USER=usuario
      - POSTGRES_PASSWORD=contra
      - POSTGRES_DB=basedatos
    ports:
      - "5432:5432"
    restart: always
